# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb19ab2d338dbee28c5db33db1cfdf0a5fcba9bd264f486d8aa20045f134bc85bd5ddb1e02a8153414b50f2cddcf62cc4c0a2452d872736b69dda9d0d3e0b334

test:
  secret_key_base: 2627e81e34e028f5a4229c1be4468ddbc65ee507750ffe10785de461456f799e53c0700d1cb37eb6065433cd98b79b899661e3bf09a17744e11236d26dfb6ae1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
